### PR TITLE
Use pythonjsonlogger.jsonlogger for python-json-logger 2.x compatibility

### LINKED ISSUE #2525: Inference server fails to import pythonjsonlogger.json — dependency floor python-json-logger>=2.0.2 is too low
**Describe the bug**
The Truss inference server imports `from pythonjsonlogger import json` (`truss/templates/shared/log_config.py`), but the `pythonjsonlogger.json` module only exists in **python-json-logger >= 3.1.0**. Truss declares `python-json-logger>=2.0.2`, so when the installed version is in the 2.x range the server crash-loops at startup and never becomes ready. It is especially easy to hit with a custom `base_image`: Truss reuses the image's venv via `python_executable_path` and does not upgrade already-satisfied deps, so a transitive `python-json-logger` 2.x (which satisfies the `>=2.0.2` floor) is left in place.

**To Reproduce**
1. Use a custom `base_image` whose venv already has `python-json-logger` 2.x (e.g. pulled transitively by another dependency).
2. `truss push`.
3. The image builds, but the model never reaches ACTIVE; the server restarts repeatedly.

**Expected behavior**
The server starts. Truss's declared dependency floor should match the module it actually imports — `python-json-logger>=3.1.0` — so resolution/installation guarantees a compatible version.

**Screenshots/Logs**

```
ImportError: cannot import name 'json' from 'pythonjsonlogger' (/.../site-packages/pythonjsonlogger/__init__.py)
Model terminated unexpectedly. Exit code: 1
```

**Desktop (please complete the following information):**
 - OS: client macOS; deployment runs Linux (Debian/Ubuntu 24.04 base image)
 - Environment versions: Python 3.12; python-json-logger 2.0.7 installed vs >=3.1.0 required
 - Truss version: 0.18.17

**Additional context**
`pythonjsonlogger.json` was introduced in python-json-logger 3.1.0; 3.x keeps `pythonjsonlogger.jsonlogger` as a deprecated back-compat shim (still present in 4.1.0), so raising the floor is backward-compatible. Workaround: add `python-json-logger>=3.1` to `config.yaml` `requirements`.

### PR DESCRIPTION
**Pull request by cretz**
## :rocket: What

- Reverts the inference server log import from `pythonjsonlogger.json` back to `pythonjsonlogger.jsonlogger`, fixing crash-loops on python-json-logger 2.x (`ImportError: cannot import name 'json' from 'pythonjsonlogger'`). Fixes #2525.
- The `pythonjsonlogger.json` module only exists in 3.1.0+, but the declared floor is `>=2.0.2`; custom base images carrying a transitive 2.x are left un-upgraded and crash. `jsonlogger` works across 2.x–4.x (retained as a deprecated shim), matching the declared floor.
- Adds a `test-lowest-direct` CI job that runs the unit suite with direct deps resolved to their declared floors, to catch this class of floor/import mismatch. Also updated a CLI-only dep to make test pass, and skipped a couple of tests during this old-version run that don't work on 3.9.

## :computer: How

- `truss/templates/shared/log_config.py`: import `jsonlogger` and use `jsonlogger.JsonFormatter` for both formatter subclasses. No floor bump; the only API used (`JsonFormatter`, `add_fields`, `format`) is present and identically-shaped on 2.x.
- `.github/workflows/pr.yml`: new job using `uv sync --resolution lowest-direct` on the min supported Python (Linux). Note: does not cover the container requirement files under `truss/templates/**`, which uv never resolves.

## :microscope: Testing

- Pinned `python-json-logger==2.0.7` and verified at runtime: `make_log_config`, both formatters, request_id/chain_request_id injection, and the uvicorn.access message rewrite all emit correct JSON.
- `truss/tests/templates/server/test_truss_server.py` passes on 2.0.7 (5 passed).
- pre-commit (ruff + mypy) clean.

### CODE REVIEW

File: .github/workflows/pr.yml [hunk 1]
```diff
@@ -74,6 +74,35 @@ jobs:
...
+          sudo mkdir -p /static-bptr && sudo chown $(whoami):$(whoami) /static-bptr
+          sudo mkdir -p /cache && sudo chown $(whoami):$(whoami) /cache
+      - run: uv sync --resolution lowest-direct
+      - name: run tests
+        run: uv run --no-sync pytest --durations=0 -m 'not integration' --junitxml=report-lowest.xml --basetemp=$RUNNER_TEMP/pytest-temp
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: always()
+        with:
+          commit: ${{ github.event.workflow_run.head_sha }}
```
[the remark this answers is not in the document]
Comment (cretz) [reply .github/workflows/pr.yml:105]: This matches existing test job

**Review by marius-baseten — APPROVED** [review]
